/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SubVue3IndexImport } from './routes/sub-vue3/index'
import { Route as SubReactIndexImport } from './routes/sub-react/index'
import { Route as SubNuxtIndexImport } from './routes/sub-nuxt/index'
import { Route as SubNextIndexImport } from './routes/sub-next/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as LoginCallbackImport } from './routes/login/callback'
import { Route as UserIndexUserIdImport } from './routes/user/index.$userId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubVue3IndexRoute = SubVue3IndexImport.update({
  id: '/sub-vue3/',
  path: '/sub-vue3/',
  getParentRoute: () => rootRoute,
} as any)

const SubReactIndexRoute = SubReactIndexImport.update({
  id: '/sub-react/',
  path: '/sub-react/',
  getParentRoute: () => rootRoute,
} as any)

const SubNuxtIndexRoute = SubNuxtIndexImport.update({
  id: '/sub-nuxt/',
  path: '/sub-nuxt/',
  getParentRoute: () => rootRoute,
} as any)

const SubNextIndexRoute = SubNextIndexImport.update({
  id: '/sub-next/',
  path: '/sub-next/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const LoginCallbackRoute = LoginCallbackImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexUserIdRoute = UserIndexUserIdImport.update({
  id: '/user/index/$userId',
  path: '/user/index/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/sub-next/': {
      id: '/sub-next/'
      path: '/sub-next'
      fullPath: '/sub-next'
      preLoaderRoute: typeof SubNextIndexImport
      parentRoute: typeof rootRoute
    }
    '/sub-nuxt/': {
      id: '/sub-nuxt/'
      path: '/sub-nuxt'
      fullPath: '/sub-nuxt'
      preLoaderRoute: typeof SubNuxtIndexImport
      parentRoute: typeof rootRoute
    }
    '/sub-react/': {
      id: '/sub-react/'
      path: '/sub-react'
      fullPath: '/sub-react'
      preLoaderRoute: typeof SubReactIndexImport
      parentRoute: typeof rootRoute
    }
    '/sub-vue3/': {
      id: '/sub-vue3/'
      path: '/sub-vue3'
      fullPath: '/sub-vue3'
      preLoaderRoute: typeof SubVue3IndexImport
      parentRoute: typeof rootRoute
    }
    '/user/index/$userId': {
      id: '/user/index/$userId'
      path: '/user/index/$userId'
      fullPath: '/user/index/$userId'
      preLoaderRoute: typeof UserIndexUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/sub-next': typeof SubNextIndexRoute
  '/sub-nuxt': typeof SubNuxtIndexRoute
  '/sub-react': typeof SubReactIndexRoute
  '/sub-vue3': typeof SubVue3IndexRoute
  '/user/index/$userId': typeof UserIndexUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/sub-next': typeof SubNextIndexRoute
  '/sub-nuxt': typeof SubNuxtIndexRoute
  '/sub-react': typeof SubReactIndexRoute
  '/sub-vue3': typeof SubVue3IndexRoute
  '/user/index/$userId': typeof UserIndexUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/': typeof LoginIndexRoute
  '/sub-next/': typeof SubNextIndexRoute
  '/sub-nuxt/': typeof SubNuxtIndexRoute
  '/sub-react/': typeof SubReactIndexRoute
  '/sub-vue3/': typeof SubVue3IndexRoute
  '/user/index/$userId': typeof UserIndexUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login/callback'
    | '/login'
    | '/sub-next'
    | '/sub-nuxt'
    | '/sub-react'
    | '/sub-vue3'
    | '/user/index/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login/callback'
    | '/login'
    | '/sub-next'
    | '/sub-nuxt'
    | '/sub-react'
    | '/sub-vue3'
    | '/user/index/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login/callback'
    | '/login/'
    | '/sub-next/'
    | '/sub-nuxt/'
    | '/sub-react/'
    | '/sub-vue3/'
    | '/user/index/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SubNextIndexRoute: typeof SubNextIndexRoute
  SubNuxtIndexRoute: typeof SubNuxtIndexRoute
  SubReactIndexRoute: typeof SubReactIndexRoute
  SubVue3IndexRoute: typeof SubVue3IndexRoute
  UserIndexUserIdRoute: typeof UserIndexUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
  SubNextIndexRoute: SubNextIndexRoute,
  SubNuxtIndexRoute: SubNuxtIndexRoute,
  SubReactIndexRoute: SubReactIndexRoute,
  SubVue3IndexRoute: SubVue3IndexRoute,
  UserIndexUserIdRoute: UserIndexUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login/callback",
        "/login/",
        "/sub-next/",
        "/sub-nuxt/",
        "/sub-react/",
        "/sub-vue3/",
        "/user/index/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login/callback": {
      "filePath": "login/callback.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/sub-next/": {
      "filePath": "sub-next/index.tsx"
    },
    "/sub-nuxt/": {
      "filePath": "sub-nuxt/index.tsx"
    },
    "/sub-react/": {
      "filePath": "sub-react/index.tsx"
    },
    "/sub-vue3/": {
      "filePath": "sub-vue3/index.tsx"
    },
    "/user/index/$userId": {
      "filePath": "user/index.$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
